//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 12:26:07 AM BRT 
//


package hpcshelf.certification.hash.component;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ColorComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ColorComplexType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="r" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="g" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *       &lt;attribute name="b" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ColorComplexType")
public class ColorComplexType {

    @XmlAttribute(name = "r", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short r;
    @XmlAttribute(name = "g", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short g;
    @XmlAttribute(name = "b", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short b;

    /**
     * Gets the value of the r property.
     * 
     */
    public short getR() {
        return r;
    }

    /**
     * Sets the value of the r property.
     * 
     */
    public void setR(short value) {
        this.r = value;
    }

    /**
     * Gets the value of the g property.
     * 
     */
    public short getG() {
        return g;
    }

    /**
     * Sets the value of the g property.
     * 
     */
    public void setG(short value) {
        this.g = value;
    }

    /**
     * Gets the value of the b property.
     * 
     */
    public short getB() {
        return b;
    }

    /**
     * Sets the value of the b property.
     * 
     */
    public void setB(short value) {
        this.b = value;
    }

}
