//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 12:26:07 AM BRT 
//


package hpcshelf.certification.hash.component;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConditionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConditionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="slice_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cond_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConditionType")
public class ConditionType {

    @XmlAttribute(name = "slice_id")
    protected String sliceId;
    @XmlAttribute(name = "cond_id", required = true)
    protected String condId;

    /**
     * Gets the value of the sliceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSliceId() {
        return sliceId;
    }

    /**
     * Sets the value of the sliceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSliceId(String value) {
        this.sliceId = value;
    }

    /**
     * Gets the value of the condId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondId() {
        return condId;
    }

    /**
     * Sets the value of the condId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondId(String value) {
        this.condId = value;
    }

}
