//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 12:26:07 AM BRT 
//


package hpcshelf.certification.hash.component;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnumeratorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnumeratorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="originRef" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="links" type="{http://www.example.org/HashComponent}EnumerableType" maxOccurs="unbounded"/>
 *         &lt;element name="visualDescription" type="{http://www.example.org/HashComponent}VisualElementAttributes"/>
 *         &lt;element name="fromRecursion" type="{http://www.example.org/HashComponent}EnumeratorFromRecursionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="varId" type="{http://www.w3.org/2001/XMLSchema}string" default="*" />
 *       &lt;attribute name="cardinality" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="fromSplit" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnumeratorType", propOrder = {
    "originRef",
    "links",
    "visualDescription",
    "fromRecursion"
})
public class EnumeratorType {

    protected List<String> originRef;
    @XmlElement(required = true)
    protected List<EnumerableType> links;
    @XmlElement(required = true)
    protected VisualElementAttributes visualDescription;
    protected EnumeratorFromRecursionType fromRecursion;
    @XmlAttribute(name = "ref", required = true)
    protected String ref;
    @XmlAttribute(name = "varId")
    protected String varId;
    @XmlAttribute(name = "cardinality")
    protected Integer cardinality;
    @XmlAttribute(name = "fromSplit", required = true)
    protected boolean fromSplit;

    /**
     * Gets the value of the originRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the originRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOriginRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOriginRef() {
        if (originRef == null) {
            originRef = new ArrayList<String>();
        }
        return this.originRef;
    }

    /**
     * Gets the value of the links property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the links property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnumerableType }
     * 
     * 
     */
    public List<EnumerableType> getLinks() {
        if (links == null) {
            links = new ArrayList<EnumerableType>();
        }
        return this.links;
    }

    /**
     * Gets the value of the visualDescription property.
     * 
     * @return
     *     possible object is
     *     {@link VisualElementAttributes }
     *     
     */
    public VisualElementAttributes getVisualDescription() {
        return visualDescription;
    }

    /**
     * Sets the value of the visualDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisualElementAttributes }
     *     
     */
    public void setVisualDescription(VisualElementAttributes value) {
        this.visualDescription = value;
    }

    /**
     * Gets the value of the fromRecursion property.
     * 
     * @return
     *     possible object is
     *     {@link EnumeratorFromRecursionType }
     *     
     */
    public EnumeratorFromRecursionType getFromRecursion() {
        return fromRecursion;
    }

    /**
     * Sets the value of the fromRecursion property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumeratorFromRecursionType }
     *     
     */
    public void setFromRecursion(EnumeratorFromRecursionType value) {
        this.fromRecursion = value;
    }

    /**
     * Gets the value of the ref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRef() {
        return ref;
    }

    /**
     * Sets the value of the ref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRef(String value) {
        this.ref = value;
    }

    /**
     * Gets the value of the varId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVarId() {
        if (varId == null) {
            return "*";
        } else {
            return varId;
        }
    }

    /**
     * Sets the value of the varId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVarId(String value) {
        this.varId = value;
    }

    /**
     * Gets the value of the cardinality property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCardinality() {
        return cardinality;
    }

    /**
     * Sets the value of the cardinality property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCardinality(Integer value) {
        this.cardinality = value;
    }

    /**
     * Gets the value of the fromSplit property.
     * 
     */
    public boolean isFromSplit() {
        return fromSplit;
    }

    /**
     * Sets the value of the fromSplit property.
     * 
     */
    public void setFromSplit(boolean value) {
        this.fromSplit = value;
    }

}
