//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 12:26:07 AM BRT 
//


package hpcshelf.certification.hash.component;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FusionsOfReplicatorsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FusionsOfReplicatorsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fusionOfReplicators" type="{http://www.example.org/HashComponent}FusionOfReplicatorsType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FusionsOfReplicatorsType", propOrder = {
    "fusionOfReplicators"
})
public class FusionsOfReplicatorsType {

    @XmlElement(required = true)
    protected List<FusionOfReplicatorsType> fusionOfReplicators;

    /**
     * Gets the value of the fusionOfReplicators property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fusionOfReplicators property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFusionOfReplicators().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FusionOfReplicatorsType }
     * 
     * 
     */
    public List<FusionOfReplicatorsType> getFusionOfReplicators() {
        if (fusionOfReplicators == null) {
            fusionOfReplicators = new ArrayList<FusionOfReplicatorsType>();
        }
        return this.fusionOfReplicators;
    }

}
