//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 12:26:07 AM BRT 
//


package hpcshelf.certification.hash.component;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FusionOfReplicatorsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FusionOfReplicatorsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="originRef" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FusionOfReplicatorsType", propOrder = {
    "eRef",
    "originRef"
})
public class FusionOfReplicatorsType {

    @XmlElement(required = true)
    protected String eRef;
    protected List<String> originRef;

    /**
     * Gets the value of the eRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERef() {
        return eRef;
    }

    /**
     * Sets the value of the eRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERef(String value) {
        this.eRef = value;
    }

    /**
     * Gets the value of the originRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the originRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOriginRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOriginRef() {
        if (originRef == null) {
            originRef = new ArrayList<String>();
        }
        return this.originRef;
    }

}
