//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 12:26:07 AM BRT 
//


package hpcshelf.certification.hash.component;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InnerRenamingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InnerRenamingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="cRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cOldName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cNewName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InnerRenamingType")
public class InnerRenamingType {

    @XmlAttribute(name = "cRef")
    protected String cRef;
    @XmlAttribute(name = "cOldName")
    protected String cOldName;
    @XmlAttribute(name = "cNewName")
    protected String cNewName;

    /**
     * Gets the value of the cRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRef() {
        return cRef;
    }

    /**
     * Sets the value of the cRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRef(String value) {
        this.cRef = value;
    }

    /**
     * Gets the value of the cOldName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOldName() {
        return cOldName;
    }

    /**
     * Sets the value of the cOldName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOldName(String value) {
        this.cOldName = value;
    }

    /**
     * Gets the value of the cNewName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNewName() {
        return cNewName;
    }

    /**
     * Sets the value of the cNewName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNewName(String value) {
        this.cNewName = value;
    }

}
