//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 12:26:07 AM BRT 
//


package hpcshelf.certification.hash.component;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InterfaceSliceRefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InterfaceSliceRefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="componentRef" type="{http://www.w3.org/2001/XMLSchema}string" default="this" />
 *       &lt;attribute name="interfaceRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sliceRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InterfaceSliceRefType")
public class InterfaceSliceRefType {

    @XmlAttribute(name = "componentRef")
    protected String componentRef;
    @XmlAttribute(name = "interfaceRef", required = true)
    protected String interfaceRef;
    @XmlAttribute(name = "sliceRef")
    protected String sliceRef;

    /**
     * Gets the value of the componentRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentRef() {
        if (componentRef == null) {
            return "this";
        } else {
            return componentRef;
        }
    }

    /**
     * Sets the value of the componentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentRef(String value) {
        this.componentRef = value;
    }

    /**
     * Gets the value of the interfaceRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterfaceRef() {
        return interfaceRef;
    }

    /**
     * Sets the value of the interfaceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterfaceRef(String value) {
        this.interfaceRef = value;
    }

    /**
     * Gets the value of the sliceRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSliceRef() {
        return sliceRef;
    }

    /**
     * Sets the value of the sliceRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSliceRef(String value) {
        this.sliceRef = value;
    }

}
