//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 12:26:07 AM BRT 
//


package hpcshelf.certification.hash.component;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hpcshelf.certification.hash.component package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Component_QNAME = new QName("http://www.example.org/HashComponent", "component");
    private final static QName _GuardTypeCondition_QNAME = new QName("", "condition");
    private final static QName _GuardTypeOr_QNAME = new QName("", "or");
    private final static QName _GuardTypeAnd_QNAME = new QName("", "and");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hpcshelf.certification.hash.component
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComponentType }
     * 
     */
    public ComponentType createComponentType() {
        return new ComponentType();
    }

    /**
     * Create an instance of {@link UnitBoundsType }
     * 
     */
    public UnitBoundsType createUnitBoundsType() {
        return new UnitBoundsType();
    }

    /**
     * Create an instance of {@link FusionsOfReplicatorsType }
     * 
     */
    public FusionsOfReplicatorsType createFusionsOfReplicatorsType() {
        return new FusionsOfReplicatorsType();
    }

    /**
     * Create an instance of {@link PortSliceType }
     * 
     */
    public PortSliceType createPortSliceType() {
        return new PortSliceType();
    }

    /**
     * Create an instance of {@link EnumeratorType }
     * 
     */
    public EnumeratorType createEnumeratorType() {
        return new EnumeratorType();
    }

    /**
     * Create an instance of {@link UnitRefType }
     * 
     */
    public UnitRefType createUnitRefType() {
        return new UnitRefType();
    }

    /**
     * Create an instance of {@link FusionType }
     * 
     */
    public FusionType createFusionType() {
        return new FusionType();
    }

    /**
     * Create an instance of {@link VersionType }
     * 
     */
    public VersionType createVersionType() {
        return new VersionType();
    }

    /**
     * Create an instance of {@link ColorComplexType }
     * 
     */
    public ColorComplexType createColorComplexType() {
        return new ColorComplexType();
    }

    /**
     * Create an instance of {@link ComponentBodyType }
     * 
     */
    public ComponentBodyType createComponentBodyType() {
        return new ComponentBodyType();
    }

    /**
     * Create an instance of {@link InterfaceParameterType }
     * 
     */
    public InterfaceParameterType createInterfaceParameterType() {
        return new InterfaceParameterType();
    }

    /**
     * Create an instance of {@link ExposePortType }
     * 
     */
    public ExposePortType createExposePortType() {
        return new ExposePortType();
    }

    /**
     * Create an instance of {@link ParameterRenaming }
     * 
     */
    public ParameterRenaming createParameterRenaming() {
        return new ParameterRenaming();
    }

    /**
     * Create an instance of {@link GuardConditionType }
     * 
     */
    public GuardConditionType createGuardConditionType() {
        return new GuardConditionType();
    }

    /**
     * Create an instance of {@link PortType }
     * 
     */
    public PortType createPortType() {
        return new PortType();
    }

    /**
     * Create an instance of {@link EnumerableType }
     * 
     */
    public EnumerableType createEnumerableType() {
        return new EnumerableType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link ProtocolCombinatorVisualType }
     * 
     */
    public ProtocolCombinatorVisualType createProtocolCombinatorVisualType() {
        return new ProtocolCombinatorVisualType();
    }

    /**
     * Create an instance of {@link RecursiveEntryType }
     * 
     */
    public RecursiveEntryType createRecursiveEntryType() {
        return new RecursiveEntryType();
    }

    /**
     * Create an instance of {@link EnumerableUnitType }
     * 
     */
    public EnumerableUnitType createEnumerableUnitType() {
        return new EnumerableUnitType();
    }

    /**
     * Create an instance of {@link SourceFileType }
     * 
     */
    public SourceFileType createSourceFileType() {
        return new SourceFileType();
    }

    /**
     * Create an instance of {@link VisualElementAttributes }
     * 
     */
    public VisualElementAttributes createVisualElementAttributes() {
        return new VisualElementAttributes();
    }

    /**
     * Create an instance of {@link BaseTypeType }
     * 
     */
    public BaseTypeType createBaseTypeType() {
        return new BaseTypeType();
    }

    /**
     * Create an instance of {@link SplitLinkType }
     * 
     */
    public SplitLinkType createSplitLinkType() {
        return new SplitLinkType();
    }

    /**
     * Create an instance of {@link InnerRenamingType }
     * 
     */
    public InnerRenamingType createInnerRenamingType() {
        return new InnerRenamingType();
    }

    /**
     * Create an instance of {@link EnumeratorFromRecursionType }
     * 
     */
    public EnumeratorFromRecursionType createEnumeratorFromRecursionType() {
        return new EnumeratorFromRecursionType();
    }

    /**
     * Create an instance of {@link FusionOfReplicatorsType }
     * 
     */
    public FusionOfReplicatorsType createFusionOfReplicatorsType() {
        return new FusionOfReplicatorsType();
    }

    /**
     * Create an instance of {@link GuardType }
     * 
     */
    public GuardType createGuardType() {
        return new GuardType();
    }

    /**
     * Create an instance of {@link InterfaceRefType }
     * 
     */
    public InterfaceRefType createInterfaceRefType() {
        return new InterfaceRefType();
    }

    /**
     * Create an instance of {@link ProtocolChoiceType }
     * 
     */
    public ProtocolChoiceType createProtocolChoiceType() {
        return new ProtocolChoiceType();
    }

    /**
     * Create an instance of {@link InterfaceSliceType }
     * 
     */
    public InterfaceSliceType createInterfaceSliceType() {
        return new InterfaceSliceType();
    }

    /**
     * Create an instance of {@link InnerComponentType }
     * 
     */
    public InnerComponentType createInnerComponentType() {
        return new InnerComponentType();
    }

    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }

    /**
     * Create an instance of {@link ComponentInUseType }
     * 
     */
    public ComponentInUseType createComponentInUseType() {
        return new ComponentInUseType();
    }

    /**
     * Create an instance of {@link UnitType }
     * 
     */
    public UnitType createUnitType() {
        return new UnitType();
    }

    /**
     * Create an instance of {@link ExtensionTypeType }
     * 
     */
    public ExtensionTypeType createExtensionTypeType() {
        return new ExtensionTypeType();
    }

    /**
     * Create an instance of {@link UnitSliceType }
     * 
     */
    public UnitSliceType createUnitSliceType() {
        return new UnitSliceType();
    }

    /**
     * Create an instance of {@link ProtocolPerformType }
     * 
     */
    public ProtocolPerformType createProtocolPerformType() {
        return new ProtocolPerformType();
    }

    /**
     * Create an instance of {@link InterfaceSliceRefType }
     * 
     */
    public InterfaceSliceRefType createInterfaceSliceRefType() {
        return new InterfaceSliceRefType();
    }

    /**
     * Create an instance of {@link SplitType }
     * 
     */
    public SplitType createSplitType() {
        return new SplitType();
    }

    /**
     * Create an instance of {@link EnumerableEntryType }
     * 
     */
    public EnumerableEntryType createEnumerableEntryType() {
        return new EnumerableEntryType();
    }

    /**
     * Create an instance of {@link EnumerableUnitSliceType }
     * 
     */
    public EnumerableUnitSliceType createEnumerableUnitSliceType() {
        return new EnumerableUnitSliceType();
    }

    /**
     * Create an instance of {@link ConditionType }
     * 
     */
    public ConditionType createConditionType() {
        return new ConditionType();
    }

    /**
     * Create an instance of {@link InterfaceType }
     * 
     */
    public InterfaceType createInterfaceType() {
        return new InterfaceType();
    }

    /**
     * Create an instance of {@link ProtocolCombinatorType }
     * 
     */
    public ProtocolCombinatorType createProtocolCombinatorType() {
        return new ProtocolCombinatorType();
    }

    /**
     * Create an instance of {@link SourceType }
     * 
     */
    public SourceType createSourceType() {
        return new SourceType();
    }

    /**
     * Create an instance of {@link ExtendsType }
     * 
     */
    public ExtendsType createExtendsType() {
        return new ExtendsType();
    }

    /**
     * Create an instance of {@link UnitConditionType }
     * 
     */
    public UnitConditionType createUnitConditionType() {
        return new UnitConditionType();
    }

    /**
     * Create an instance of {@link EnumeratorRefType }
     * 
     */
    public EnumeratorRefType createEnumeratorRefType() {
        return new EnumeratorRefType();
    }

    /**
     * Create an instance of {@link ParameterSupplyType }
     * 
     */
    public ParameterSupplyType createParameterSupplyType() {
        return new ParameterSupplyType();
    }

    /**
     * Create an instance of {@link ProtocolPerformVisualType }
     * 
     */
    public ProtocolPerformVisualType createProtocolPerformVisualType() {
        return new ProtocolPerformVisualType();
    }

    /**
     * Create an instance of {@link ImplementsType }
     * 
     */
    public ImplementsType createImplementsType() {
        return new ImplementsType();
    }

    /**
     * Create an instance of {@link InterfacePortType }
     * 
     */
    public InterfacePortType createInterfacePortType() {
        return new InterfacePortType();
    }

    /**
     * Create an instance of {@link UnitActionType }
     * 
     */
    public UnitActionType createUnitActionType() {
        return new UnitActionType();
    }

    /**
     * Create an instance of {@link SplitEnumeratorType }
     * 
     */
    public SplitEnumeratorType createSplitEnumeratorType() {
        return new SplitEnumeratorType();
    }

    /**
     * Create an instance of {@link ComponentHeaderType }
     * 
     */
    public ComponentHeaderType createComponentHeaderType() {
        return new ComponentHeaderType();
    }

    /**
     * Create an instance of {@link EnumerableComponentType }
     * 
     */
    public EnumerableComponentType createEnumerableComponentType() {
        return new EnumerableComponentType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComponentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/HashComponent", name = "component")
    public JAXBElement<ComponentType> createComponent(ComponentType value) {
        return new JAXBElement<ComponentType>(_Component_QNAME, ComponentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConditionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "condition", scope = GuardType.class)
    public JAXBElement<ConditionType> createGuardTypeCondition(ConditionType value) {
        return new JAXBElement<ConditionType>(_GuardTypeCondition_QNAME, ConditionType.class, GuardType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GuardType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "or", scope = GuardType.class)
    public JAXBElement<GuardType> createGuardTypeOr(GuardType value) {
        return new JAXBElement<GuardType>(_GuardTypeOr_QNAME, GuardType.class, GuardType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GuardType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "and", scope = GuardType.class)
    public JAXBElement<GuardType> createGuardTypeAnd(GuardType value) {
        return new JAXBElement<GuardType>(_GuardTypeAnd_QNAME, GuardType.class, GuardType.class, value);
    }

}
