//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 12:26:07 AM BRT 
//


package hpcshelf.certification.hash.component;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PortSliceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PortSliceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="sRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PortSliceType")
public class PortSliceType {

    @XmlAttribute(name = "sRef")
    protected String sRef;
    @XmlAttribute(name = "pRef")
    protected String pRef;

    /**
     * Gets the value of the sRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSRef() {
        return sRef;
    }

    /**
     * Sets the value of the sRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSRef(String value) {
        this.sRef = value;
    }

    /**
     * Gets the value of the pRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRef() {
        return pRef;
    }

    /**
     * Sets the value of the pRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRef(String value) {
        this.pRef = value;
    }

}
