//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 12:26:07 AM BRT 
//


package hpcshelf.certification.hash.component;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProtocolChoiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProtocolChoiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="par" type="{http://www.example.org/HashComponent}ProtocolCombinatorVisualType"/>
 *         &lt;element name="seq" type="{http://www.example.org/HashComponent}ProtocolCombinatorVisualType"/>
 *         &lt;element name="alt" type="{http://www.example.org/HashComponent}ProtocolCombinatorVisualType"/>
 *         &lt;element name="perform" type="{http://www.example.org/HashComponent}ProtocolPerformVisualType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProtocolChoiceType", propOrder = {
    "par",
    "seq",
    "alt",
    "perform"
})
public class ProtocolChoiceType {

    protected ProtocolCombinatorVisualType par;
    protected ProtocolCombinatorVisualType seq;
    protected ProtocolCombinatorVisualType alt;
    protected ProtocolPerformVisualType perform;

    /**
     * Gets the value of the par property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolCombinatorVisualType }
     *     
     */
    public ProtocolCombinatorVisualType getPar() {
        return par;
    }

    /**
     * Sets the value of the par property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolCombinatorVisualType }
     *     
     */
    public void setPar(ProtocolCombinatorVisualType value) {
        this.par = value;
    }

    /**
     * Gets the value of the seq property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolCombinatorVisualType }
     *     
     */
    public ProtocolCombinatorVisualType getSeq() {
        return seq;
    }

    /**
     * Sets the value of the seq property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolCombinatorVisualType }
     *     
     */
    public void setSeq(ProtocolCombinatorVisualType value) {
        this.seq = value;
    }

    /**
     * Gets the value of the alt property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolCombinatorVisualType }
     *     
     */
    public ProtocolCombinatorVisualType getAlt() {
        return alt;
    }

    /**
     * Sets the value of the alt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolCombinatorVisualType }
     *     
     */
    public void setAlt(ProtocolCombinatorVisualType value) {
        this.alt = value;
    }

    /**
     * Gets the value of the perform property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolPerformVisualType }
     *     
     */
    public ProtocolPerformVisualType getPerform() {
        return perform;
    }

    /**
     * Sets the value of the perform property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolPerformVisualType }
     *     
     */
    public void setPerform(ProtocolPerformVisualType value) {
        this.perform = value;
    }

}
