//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 12:26:07 AM BRT 
//


package hpcshelf.certification.hash.component;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProtocolPerformType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProtocolPerformType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.example.org/HashComponent}ProtocolType">
 *       &lt;attribute name="action_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="slice_id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProtocolPerformType")
@XmlSeeAlso({
    ProtocolPerformVisualType.class
})
public class ProtocolPerformType
    extends ProtocolType
{

    @XmlAttribute(name = "action_id")
    protected String actionId;
    @XmlAttribute(name = "slice_id")
    protected String sliceId;

    /**
     * Gets the value of the actionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionId() {
        return actionId;
    }

    /**
     * Sets the value of the actionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionId(String value) {
        this.actionId = value;
    }

    /**
     * Gets the value of the sliceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSliceId() {
        return sliceId;
    }

    /**
     * Sets the value of the sliceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSliceId(String value) {
        this.sliceId = value;
    }

}
