//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 12:26:07 AM BRT 
//


package hpcshelf.certification.hash.component;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SplitType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SplitType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="splitLink" type="{http://www.example.org/HashComponent}SplitLinkType" maxOccurs="unbounded"/>
 *         &lt;element name="splitEnumerator" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="originRef" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="eRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="n" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="cRefPermutation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SplitType", propOrder = {
    "splitLink",
    "splitEnumerator",
    "originRef"
})
public class SplitType {

    @XmlElement(required = true)
    protected List<SplitLinkType> splitLink;
    @XmlElement(required = true)
    protected List<String> splitEnumerator;
    protected List<String> originRef;
    @XmlAttribute(name = "eRef", required = true)
    protected String eRef;
    @XmlAttribute(name = "n")
    protected Integer n;
    @XmlAttribute(name = "cRefPermutation")
    protected String cRefPermutation;

    /**
     * Gets the value of the splitLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the splitLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSplitLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SplitLinkType }
     * 
     * 
     */
    public List<SplitLinkType> getSplitLink() {
        if (splitLink == null) {
            splitLink = new ArrayList<SplitLinkType>();
        }
        return this.splitLink;
    }

    /**
     * Gets the value of the splitEnumerator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the splitEnumerator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSplitEnumerator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSplitEnumerator() {
        if (splitEnumerator == null) {
            splitEnumerator = new ArrayList<String>();
        }
        return this.splitEnumerator;
    }

    /**
     * Gets the value of the originRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the originRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOriginRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOriginRef() {
        if (originRef == null) {
            originRef = new ArrayList<String>();
        }
        return this.originRef;
    }

    /**
     * Gets the value of the eRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERef() {
        return eRef;
    }

    /**
     * Sets the value of the eRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERef(String value) {
        this.eRef = value;
    }

    /**
     * Gets the value of the n property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getN() {
        return n;
    }

    /**
     * Sets the value of the n property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setN(Integer value) {
        this.n = value;
    }

    /**
     * Gets the value of the cRefPermutation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRefPermutation() {
        return cRefPermutation;
    }

    /**
     * Sets the value of the cRefPermutation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRefPermutation(String value) {
        this.cRefPermutation = value;
    }

}
