//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 12:26:07 AM BRT 
//


package hpcshelf.certification.hash.component;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SupportedKinds.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SupportedKinds">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Data"/>
 *     &lt;enumeration value="Computation"/>
 *     &lt;enumeration value="Synchronizer"/>
 *     &lt;enumeration value="Platform"/>
 *     &lt;enumeration value="Environment"/>
 *     &lt;enumeration value="Qualifier"/>
 *     &lt;enumeration value="Application"/>
 *     &lt;enumeration value="Enumerator"/>
 *     &lt;enumeration value="Facet"/>
 *     &lt;enumeration value="Domain"/>
 *     &lt;enumeration value="Topology"/>
 *     &lt;enumeration value="value"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SupportedKinds")
@XmlEnum
public enum SupportedKinds {

    @XmlEnumValue("Data")
    DATA("Data"),
    @XmlEnumValue("Computation")
    COMPUTATION("Computation"),
    @XmlEnumValue("Synchronizer")
    SYNCHRONIZER("Synchronizer"),
    @XmlEnumValue("Platform")
    PLATFORM("Platform"),
    @XmlEnumValue("Environment")
    ENVIRONMENT("Environment"),
    @XmlEnumValue("Qualifier")
    QUALIFIER("Qualifier"),
    @XmlEnumValue("Application")
    APPLICATION("Application"),
    @XmlEnumValue("Enumerator")
    ENUMERATOR("Enumerator"),
    @XmlEnumValue("Facet")
    FACET("Facet"),
    @XmlEnumValue("Domain")
    DOMAIN("Domain"),
    @XmlEnumValue("Topology")
    TOPOLOGY("Topology"),
    @XmlEnumValue("value")
    VALUE("value");
    private final String value;

    SupportedKinds(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SupportedKinds fromValue(String v) {
        for (SupportedKinds c: SupportedKinds.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
