//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 12:26:07 AM BRT 
//


package hpcshelf.certification.hash.component;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnitRefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnitRefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="cRef" type="{http://www.w3.org/2001/XMLSchema}string" default="this" />
 *       &lt;attribute name="uRef" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="slice_replica" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="replica" type="{http://www.w3.org/2001/XMLSchema}int" fixed="0" />
 *       &lt;attribute name="inner_replica" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnitRefType")
@XmlSeeAlso({
    UnitSliceType.class
})
public class UnitRefType {

    @XmlAttribute(name = "cRef")
    protected String cRef;
    @XmlAttribute(name = "uRef", required = true)
    protected String uRef;
    @XmlAttribute(name = "slice_replica")
    protected Integer sliceReplica;
    @XmlAttribute(name = "replica")
    protected Integer replica;
    @XmlAttribute(name = "inner_replica")
    protected Integer innerReplica;

    /**
     * Gets the value of the cRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCRef() {
        if (cRef == null) {
            return "this";
        } else {
            return cRef;
        }
    }

    /**
     * Sets the value of the cRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCRef(String value) {
        this.cRef = value;
    }

    /**
     * Gets the value of the uRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURef() {
        return uRef;
    }

    /**
     * Sets the value of the uRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURef(String value) {
        this.uRef = value;
    }

    /**
     * Gets the value of the sliceReplica property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getSliceReplica() {
        if (sliceReplica == null) {
            return  0;
        } else {
            return sliceReplica;
        }
    }

    /**
     * Sets the value of the sliceReplica property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSliceReplica(Integer value) {
        this.sliceReplica = value;
    }

    /**
     * Gets the value of the replica property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getReplica() {
        if (replica == null) {
            return  0;
        } else {
            return replica;
        }
    }

    /**
     * Sets the value of the replica property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReplica(Integer value) {
        this.replica = value;
    }

    /**
     * Gets the value of the innerReplica property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getInnerReplica() {
        if (innerReplica == null) {
            return  0;
        } else {
            return innerReplica;
        }
    }

    /**
     * Sets the value of the innerReplica property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInnerReplica(Integer value) {
        this.innerReplica = value;
    }

}
