//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.06 at 12:26:07 AM BRT 
//


package hpcshelf.certification.hash.component;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VisualElementAttributes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VisualElementAttributes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="color" type="{http://www.example.org/HashComponent}ColorComplexType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="x" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="y" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="w" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="h" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisualElementAttributes", propOrder = {
    "color"
})
public class VisualElementAttributes {

    protected ColorComplexType color;
    @XmlAttribute(name = "x", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long x;
    @XmlAttribute(name = "y", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long y;
    @XmlAttribute(name = "w", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long w;
    @XmlAttribute(name = "h", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long h;

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link ColorComplexType }
     *     
     */
    public ColorComplexType getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColorComplexType }
     *     
     */
    public void setColor(ColorComplexType value) {
        this.color = value;
    }

    /**
     * Gets the value of the x property.
     * 
     */
    public long getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     */
    public void setX(long value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     */
    public long getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     */
    public void setY(long value) {
        this.y = value;
    }

    /**
     * Gets the value of the w property.
     * 
     */
    public long getW() {
        return w;
    }

    /**
     * Sets the value of the w property.
     * 
     */
    public void setW(long value) {
        this.w = value;
    }

    /**
     * Gets the value of the h property.
     * 
     */
    public long getH() {
        return h;
    }

    /**
     * Sets the value of the h property.
     * 
     */
    public void setH(long value) {
        this.h = value;
    }

}
