namespace br.ufc.mdcc.hpcshelf.certifier.impl.computation.CertfierImpl.visitor{

public enum CertifierOrchestrationOperation {

	ORCHESTRATION,
	SEQUENCEOPER, PARALLELOPER, SELECTOPER, SWITCHOPER, REPEATOPER,
	STARTOPER, WAITOPER, CANCELOPER, PERFORMOPER, SKIPOPER, BREAKOPER, CONTINUEOPER, 
	ACTION, ID,
	OPERATION,
	RESOLVE, DEPLOY, INSTANTIATE, RELEASE, COMPUTE,
	ACTIONID,
	CHOICE,
}
}